name: eyecare
description: EyeCare - Intelligent Eye Disease Assessment
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cupertino_icons: ^1.0.6
  iconsax_flutter: ^1.0.1
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  image_picker: ^1.0.0
  image_cropper: ^11.0.0
  url_launcher: ^6.3.2
  flutter_nsd: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - images/eye_logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/eye_logo.png"
  adaptive_icon_background: "#4A90E2"
  adaptive_icon_foreground: "images/eye_logo.png"